version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnpmjs.org
    ports:
      - "7001:7001"
      - "7002:7002"
    deploy:
      mode: replicated
      replicas: 2
    labels:
      aliyun.routing.port_7001: cnpm-registry
      aliyun.routing.port_7002: cnpm-web
